defaults:
  - base_train
  - _self_

seed: 0

train:
  datasets:
    - path: pretrain_datasets/single_table_stage1.h5
      weight: null
      sampled_columns: 0
      targets_per_subset: 0
      group_size_for_augment_data: 1

  num_steps: 75000
  batch_size: 8
  lr: 0.0005
  steps_per_eval: 200
  save_every_evals: 30
  load_model_path: null
  save_model_path: checkpoints/RDBPFN_single/model.pt 

model:
  type: base
  embedding_size: 96
  num_attention_heads: 4
  mlp_hidden_size: 192
  num_layers: 6
  num_outputs: 2
  num_category_buckets: 10
  per_column_embeddings: false
  sort_category_embeddings: false
  invariant_noise_encoder: false
  dual_feature_attention: false
  category_as_numeric: false

eval:
  csv_dirs: [datasets/clf] 

wandb:
  enabled: false
  project: RDBPFN
  run_name: RDBPFN_single

