import shutil
import pandas as pd
import numpy as np
import yaml
from pathlib import Path
import logging

import dbinfer_bench as dbb
from dbinfer_bench.rdb_dataset import DBBRDBDataset
from dbinfer_bench.dataset_meta import (
    DBBTableSchema,
    DBBRDBDatasetMeta,
    DBBColumnSchema,
    DBBTaskMeta,
)

from ..yaml_utils import load_pyd, save_pyd
from ..device import get_device_info
from ..preprocess.transform_preprocess import (
    RDBTransformPreprocess,
    RDBTransformPreprocessConfig,
)
from ..preprocess.dfs.dfs_preprocess import (
    DFSPreprocess,
    DFSPreprocessConfig,
)


DTYPE_MAP = {
    "Categorical": "category",
    "Numerical": "float",
    "Text": "text",
    "DateTime": "datetime",
    "Other": "text",
}
def dataframe_to_rdb_dataset(
    dataframe: pd.DataFrame,
    name: str,
    target_column: str,
    time_column: str,
    column_type_dict: dict,
    path: Path,
):
    """
    Build a DBInfer-Bench dataset for the given table with config generated
    by make_schema() in the directory `path`.
    """
    column_type_dict = {k: v for k, v in column_type_dict.items() if v != "null"}
    column_config = []
    for k, v in column_type_dict.items():
        if v == "ID":
            column_config.append({
                "name": k,
                "dtype": "foreign_key",
                "link_to": f"{k}.key",
            })
        else:
            column_config.append({
                "name": k,
                "dtype": DTYPE_MAP[v],
            })

    path.mkdir(exist_ok=True, parents=True)
    data_path = path / "data_train.pqt"
    dataframe.to_parquet(data_path)
    # The current DFS pipeline requires the DBB dataset to have a training,
    # validation, and test table, so we fake the latter two.
    dummy = dataframe.iloc[:0]
    dummy.to_parquet(path / "data_validation.pqt")
    dummy.to_parquet(path / "data_test.pqt")

    column_schemas = [DBBColumnSchema.parse_obj(c) for c in column_config]
    table_schema = DBBTableSchema(
        name=name,
        source="data_train.pqt",
        format="parquet",
        columns=column_schemas,
        time_column=time_column,
    )
    task_meta = DBBTaskMeta(
        name=target_column,
        source=str("data_{split}.pqt"),
        format="parquet",
        columns=column_schemas,
        time_column=time_column,
        target_column=target_column,
        target_table=name,
        # These two arguments doesn't matter for DFS, but still required for
        # our existing Tab2Graph pipeline no matter what.  So we feed in
        # two random ones.
        evaluation_metric="rmse",
        task_type="regression",
    )

    dataset_meta = DBBRDBDatasetMeta(
        dataset_name=name,
        tables=[table_schema],
        tasks=[task_meta]
    )

    save_pyd(dataset_meta, path / "metadata.yaml")


# From configs/transform/pre-dfs.yaml
PRE_DFS_TRANSFORM_CONFIG = RDBTransformPreprocessConfig.parse_obj({
    "transforms": [
        {"name": "handle_dummy_table"},
        {"name": "key_mapping"},
        {
            "name": "column_transform_chain",
            "config": {
                "transforms": [
                    {"name": "canonicalize_numeric"},
                    {"name": "canonicalize_datetime"},
                    {"name": "glove_text_embedding"},
                ]
            },
        }
    ]
})
def make_dfs_config(depth: int):
    return DFSPreprocessConfig.parse_obj({
        "dfs": {
            "max_depth": depth,
            "use_cutoff_time": True,
            "engine": "dfs2sql",
        }
    })


def rdb_dataset_to_dataframe(path: Path):
    """
    Extract the dataframe from a DBInfer-Bench dataset generated by DFS.
    """
    meta = load_pyd(DBBRDBDatasetMeta, path / "metadata.yaml")
    assert len(meta.tasks) == 1
    data = np.load(path / meta.tasks[0].source.format(split="train"), allow_pickle=True)
    df_data = {}
    for k, v in data.items():
        if v.ndim > 1:
            v = v.reshape((v.shape[0], -1))
            for i in range(v.shape[1]):
                df_data[f"{k}_{i}"] = v[:, i]
        else:
            df_data[k] = v
    df = pd.DataFrame(df_data)
    return df


def launch_pre_dfs(path: Path, output_path: Path):
    """
    Launch the pre-DFS processing for the DBInfer-Bench dataset and output
    the result at a separate directory.
    """
    device = get_device_info()
    logging.info("Loading data ...")
    dataset = dbb.load_rdb_data(path)

    logging.info("Creating preprocess for pre-DFS transform...")
    preprocess = RDBTransformPreprocess(PRE_DFS_TRANSFORM_CONFIG)

    preprocess.run(dataset, output_path, device)


def launch_dfs(path: Path, output_path: Path, depth: int):
    """
    Run DFS on the DBInfer-Bench dataset and output the result at a separate
    directory.
    """
    device = get_device_info()
    logging.info("Loading data ...")
    dataset = dbb.load_rdb_data(path)

    logging.info("Running DFS...")
    preprocess = DFSPreprocess(make_dfs_config(depth))

    preprocess.run(dataset, output_path, device)


def run_dfs(input_df, df_name, target_column, time_column, column_type_dict, depth):
    dataframe_to_rdb_dataset(
        input_df,
        df_name,
        target_column,
        time_column,
        column_type_dict,
        Path('__workspace__/rdb'),
    )
    launch_pre_dfs(Path('__workspace__/rdb'), Path('__workspace__/pre_dfs'))
    launch_dfs(Path('__workspace__/pre_dfs'), Path('__workspace__/dfs'), depth)
    output_df = rdb_dataset_to_dataframe(Path('__workspace__/dfs'))
    return output_df
