num_rows:
  default: 1000
  parse_rules:
    - max_input: 100
      multiplier: 10.0
      offset: 1000
    - max_input: 200000
      multiplier: 0.015
      offset: 2000
    - multiplier: 0.0
      offset: 5000
  fluctuation_ratio: 0.2
  min: 1000
  max: 5000

num_cols:
  default: 5
  parse_rules:
    min_threshold: 8
    min_value: 8
    max_threshold: 12
    max_value: 12
  fluctuation_ratio: 1.0
  min: 8
  max: 12
